import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'RJRestoDemo',
  description: 'Generated by RJSEO',
  icons: {
    icon: '/favicon.png', // Sesuaikan dengan nama file di folder public
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="id">
      <body>{children}</body>
    </html>
  );
}